name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        env:
          # Asegura que NODE_ENV es production durante el build
          NODE_ENV: production
      
      - name: Create .nojekyll file
        run: touch out/.nojekyll
      
      - name: Deploy with gh-pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d out -u "github-actions-bot <support+actions@github.com>" --dotfiles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 